// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/candbright/go-core/rest"
	"github.com/candbright/wechat-robot/internal/server/dao"
	"github.com/candbright/wechat-robot/internal/server/db"
	"github.com/candbright/wechat-robot/internal/server/handler"
	"github.com/candbright/wechat-robot/internal/server/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func setupIdiomHandler() *handler.IdiomHandler {
	dbDB := db.NewDB()
	idiomDao := &dao.IdiomDao{
		DB: dbDB,
	}
	idiomService := &service.IdiomService{
		IdiomDao: idiomDao,
	}
	idiomHandler := &handler.IdiomHandler{
		IdiomService: idiomService,
	}
	return idiomHandler
}

// wire.go:

func RegisterHandlers(engine *gin.Engine) {
	rest.RegisterHandler(engine, "idiom", setupIdiomHandler())
}
